// Language translations
export const translations = {
    en: {
        //Header:
        en: "EN",
        de: "DE",
        services: "services",
        insights: "insights",
        //start_non-plan Website:
        start_welcome: "Welcome to non-plan",
        start_innovateHeading: "Transforming the AEC Industry with Innovation: Discover How We Make an Impact",
        start_innovateText: "Tailor-Made Digital Solutions for AEC Excellence: Streamlining Workflows, Automating Tasks, and Enhancing Visualization with Custom Tools for Architecture, Engineering, and Construction Professionals",
        start_introPlatform: "Simplify AEC Management with the Non-Plan Platform: Coming soon, this app will streamline workflows, track projects, and visualize sustainable solutions—all in one place.",
        start_platformText: "The Non-Plan WebApp is designed to simplify and accelerate project management in the AEC industry. It integrates a range of advanced tools to streamline workflows and improve productivity, from project tracking and task management to automated checks and feasibility assessments. Our web app empowers teams to track progress, collaborate seamlessly, and make data-driven decisions faster than ever before. The app also includes sophisticated capabilities such as automated plausibility modeling based on location and the generation of new geometries to visualize sustainable building practices.",
        start_solutionsIntro: "Tailor-Made Digital Solutions for AEC Excellence: Streamlining Workflows, Automating Tasks, and Enhancing Visualization with Custom Tools for Architecture, Engineering, and Construction Professionals.",
        start_solutionsText: "At Non-Plan, we don't just build tools – we create solutions that address the unique challenges of the AEC industry. Whether you're working in architecture, engineering, or construction, our services can help optimize your processes. We offer:",
        start_solutionsList1:"• Custom web applications that integrate into your existing workflows.",
        start_solutionsList2:"• Grasshopper and Python automation scripts to streamline repetitive tasks.",
        start_solutionsList3:"• Advanced BIM and CAD consulting for creating and managing intelligent building models.",
        start_solutionsList4:"• Specialized AR tools for visualizing designs and data in immersive environments.",
        start_whoTitle: "Who We Are",
        start_whoText: "non-plan is a team of architects, designers, and innovators dedicated to redefining the AEC industry through digital transformation and creative collaboration.Our collective expertise bridges the gap between traditional architectural practice and cutting-edge technology, fostering a culture of experimentation and innovation.",
        start_projectsTitle: "Projects and Collaborations",
        start_projectsText: "non-plan is a team of architects, designers, and innovators dedicated to redefining the AEC industry through digital transformation and creative collaboration.Our collective expertise bridges the gap between traditional architectural practice and cutting-edge technology, fostering a culture of experimentation and innovation.",
        start_accessTitle: "Access the non-plan Platform",
        start_accessText: "Unlock the full potential of your projects with the non-plan WebApp. Our platform offers a wide range of features to streamline your project management, automate workflows, and generate sustainable design solutions. Whether you're a project manager, architect, contractor, or developer, our web application can help you optimize your work processes and make informed decisions.",
        start_logIn: "Log in to Non-Plan Platform",
        start_loginWelcome1: "Welcome",
        start_loginWelcome2: "Login to the non-plan Platform",
        start_forgotPassword: "Forgot your password?",
        start_continue: "Continue",
        start_newAccount: "Don't have an account?",
        start_UsernameEmail: "Username or email address",
        start_Password: "Password",
        start_Collaborations: "We have proudly worked with the following companies and public institutions , delivering impactful solutions",
        start_Collaborations2: "These collaborations highlight our commitment to bridging innovation and sustainability within the AEC industry.",
        start_innovateText2:"Tailor-Made Digital Solutions for AEC Excellence: Streamlining Workflows, Automating Tasks, and Enhancing Visualization with Custom Tools for Architecture, Engineering, and Construction Professionals.(Photo by Marta Buso)",
        start_AR:"Augmented Reality",
        start_AREngie:"Engie Habegger Project: Swissbau 2022 AR experience.",
        start_ARLiechtenstein:"University of Liechtenstein Biennale App: Highlighting e-waste connections between Liechtenstein and Ghana.University of Liechtenstein Biennale App: Highlighting e-waste connections between Liechtenstein and Ghana.(Photo by Marta Buso)",
        start_Hohrainli: "Parametric study for the efficient positioning of reused facade elements, created using Grasshopper/Python for the research project GartenPark Hohrainli by the Institute for Environment and Natural Resources at ZHAW.",
        start_Generator: "Parametric study for generating a compatibility program that integrates different spaces, inspired by Cedric Price and presented at HSLU Luzern.",
        start_GIS: "GIS Importer for Archicad: A Grasshopper script commissioned by OOS that reads GIS data, including topography and materials, and imports 3D landscape elements into Archicad, separating them by material and including buildings.",
        start_Shade: "Shadow Overlap Calculator for Grasshopper: A script commissioned by OOS that calculates overlapping shadows over a 3-hour period, in accordance with Kanton Zurich regulations.",
        start_PythonMat: "Material Room Tags for Archicad: A Python script commissioned by OOS that automates room tags for materials directly within Archicad.",
        start_Chaos: "Circular Chaos, an application to replace geometries from reusable element lists",
        start_ServicesTitle: "Services",
        start_service1Titel:"Plugin Development",
        start_service2Titel:"Web Applications",
        start_service3Titel:"VR/AR Apps",
        start_service4Titel:"BIM Consulting",
        start_service1Content: "We specialize in creating bespoke plugins for tools like Archicad, Rhinoceros, and Grasshopper to cater to the unique needs of the AEC industry. By closely collaborating with clients, we identify bottlenecks and inefficiencies, then craft custom solutions that seamlessly integrate into existing workflows. Our plugins enhance functionality, streamline repetitive tasks, and solve complex challenges, ensuring your tools are more powerful, adaptable, and efficient in handling intricate design and engineering projects.",
        start_service2Content: "We design and build custom applications that empower teams to work smarter, not harder. By translating complex processes into user-friendly interfaces, we enable you to access your models, data, and tools anytime, anywhere. Our solutions are collaborative, scalable, and tailored to fit seamlessly into your workflows, making project management, data visualization, and team communication more efficient. We transform your digital platform into one that boosts productivity and keeps everyone aligned.",
        start_service3Content: "Harness the power of virtual and augmented reality to elevate your designs and presentations. Using Unity, we develop immersive apps that allow you to visualize, interact with, and refine your models in real time. Whether you’re exploring materials, testing design variations, or showcasing ideas to clients, our VR/AR solutions enable you to make informed decisions with confidence. We focus on creating intuitive, impactful experiences that bring your projects to life and facilitate better communication and understanding.",
        start_service4Content: "With years of experience teaching and working with leading architecture firms, we  provide comprehensive BIM consulting services. From optimizing  workflows to implementing advanced modeling strategies tailor-made for your company, we help you unlock the full potential of BIM technology. Our expertise ensures your  projects are delivered more efficiently, with fewer errors and better coordination across teams. Whether you’re adopting BIM for the first  time or refining your existing processes, we provide the guidance and  tools you need to succeed.",
        start_npInfoSoon: "more information coming soon...",
        start_Mbuso_credit: "Photo by Marta Buso",
        start_OOS_credit: "Script for the 'Josef will wohnen' project, written for OOS",
        sidebar_projects: "Projects",
        sidebar_users: "Users",
        sidebar_dashboard: "Dashboard",
        sidebar_tasks: "Tasks",
        sidebar_calendar: "Calendar",
        sidebar_documents: "Documents",
        sidebar_tools: "Tools",
        projects_status: "Status",
        projects_role: "Role",
        projects_cost: "Cost",
        projects_progress: "Progress",
        projects_new: "New Project",
        projects_name: "Name",
        projects_name_placeholder: "What's the name of your project?",
        projects_name_tip: "TIP give it a short name",
        projects_description: "Description",
        projects_description_placeholder: "Give your project a nice description!",
        projects_location: "Location",
        projects_location_placeholder: "Where is your project located?",
        projects_cost_placeholder: "What's the estimated cost of the project?",
        projects_cost_tip: "Estimated cost of the project",
        projects_progress_placeholder: "What's the estimated completion progress of the project?",
        projects_progress_tip: "Estimated progress percentage of the project",
        projects_role_not_defined: "not defined",
        projects_role_architect: "Architect",
        projects_role_engineer: "Engineer",
        projects_role_developer: "Developer",
        projects_status_pending: "Pending",
        projects_status_active: "Active",
        projects_status_finished: "Finished",
        projects_status_onhold: "On Hold",
        projects_phase: "Design Phase",
        projects_phase_design: "Design",
        projects_phase_construction_project: "Construction project",
        projects_phase_execution: "Execution",
        projects_phase_construction: "Construction",
        projects_start_date: "Start Date",
        projects_finish_date: "Finish Date",
        projects_cancel: "Cancel",
        projects_accept: "Accept",
        projects_error: "Error",
        projects_confirm_delete_task: "Are you sure you want to delete the task:",
        projects_confirm_delete_user: "Are you sure you want to delete the user",
        projects_no_description: "No description provided.",
        projects_no_status: "No status provided.",
        projects_no_cost: "No cost provided.",
        projects_no_role: "No role provided.",
        projects_no_start_date: "No start date provided.",
        projects_no_finish_date: "No finish date provided.",
        projects_no_users_assigned: "No users assigned to this project.",
        projects_no_todos: "No to-dos for this project.",
        projects_search_todos: "Search To-Do's by name",
        projects_assigned_users: "Assigned Users",
        projects_todo: "To-Do",
        projects_show_todo: "Show To-Do",
        projects_show_assigned_users: "Show Assigned Users",
        projects_remove_user: "Remove user from project",
        projects_unknown_user: "Unknown User",
        projects_add_task: "Add Task",
        projects_edit_task: "Edit Task",
        projects_tip_short_title: "TIP give it a short title",
        projects_priority: "Priority",
        projects_priority_high: "High",
        projects_priority_standard: "Standard",
        projects_priority_low: "Low",
        projects_estimated_hours: "Estimated hours",
        projects_estimated_hours_placeholder: "Estimated hours for the task",
        projects_estimated_hours_tip: "Estimated hours for the task",
        projects_actual_hours: "Actual hours",
        projects_actual_hours_placeholder: "Hours used so far",
        projects_actual_hours_tip: "Hours used so far",
        projects_responsible_person: "Responsible Person",
        projects_select_responsible: "Select responsible person",
        projects_created_by: "Created By",
        projects_select_creator: "Select creator",
        projects_due_date: "Due Date",
        projects_dependencies: "Dependencies",
        projects_dependencies_tip: "Comma-separated task IDs",
        projects_comments: "Comments",
        projects_comments_placeholder: "Add any clarification comment",
        projects_edit_project: "Edit Project",
        projects_role_in_project: "Role in this project",
        projects_role_placeholder: "e.g. Project Lead, Consultant...",
        projects_assign_user: "Assign User to Project",
        projects_user: "User",
        projects_select_user: "Select user",
        projects_assign: "Assign",
        projects_change: "Change",
        projects_delete: "Delete",
        users_new_user: "New User",
        users_change_user: "Change User",
        users_name: "Name",
        users_surname: "Surname",
        users_email: "Email Address",
        users_phone: "Telephone Number",
        users_role: "Role",
        users_access: "Access rights",
        users_access_admin: "Administrator",
        users_access_editor: "Editor",
        users_access_guest: "Guest",
        users_company: "Company",
        users_select_company: "Select company",
        users_new_company: "New Company",
        users_company_name: "Company Name",
        users_company_address: "Company Address",
        users_company_email: "Contact Email",
        users_company_phone: "Telephone Number",
        users_edit_company: "Edit Company",
        users_confirm_delete_user: "Are you sure you want to delete the user",
        users_confirm_delete_company: "Are you sure you want to delete the company",
        users_delete: "Delete",
        users_delete_user: "Delete user",
        users_delete_company: "Delete company",
        users_total_number: "Total number of",
        users_companies: "Companies",
        users_user_name: "User name",
        users_show_companies: "Show Companies",
        users_show_users: "Show Users",
        projects_title: "Title",
        projects_all_projects: "All Projects",
    },
    de: {
        //Header:
        en: "EN",
        de: "DE",
        projects_title: "Titel",
        projects_all_projects: "Alle Projekte",
        search_projects: "Projekte suchen",
        search_users: "Benutzer suchen",
        search_tasks: "Aufgaben suchen",
        search_companies: "Firmen suchen",
        services: "Dienstleistungen",
        insights: "Einblicke",
        //start_non-plan Website:
        start_welcome: "Willkommen bei non-plan",
        start_innovateHeading: "Transformation der AEC-Branche durch Innovation: Entdecken Sie, wie wir einen Unterschied machen",
        start_innovateText: "Maßgeschneiderte digitale Lösungen für AEC-Exzellenz: Optimierung von Arbeitsabläufen, Automatisierung von Aufgaben und Verbesserung der Visualisierung mit benutzerdefinierten Tools für Architektur-, Ingenieur- und Bauprofis",
        start_introPlatform: "Vereinfachen Sie das AEC-Management mit der Non-Plan-Plattform: Bald verfügbar, wird diese App Arbeitsabläufe optimieren, Projekte verfolgen und nachhaltige Lösungen visualisieren - alles an einem Ort.",
        start_platformText: "Die Non-Plan WebApp wurde entwickelt, um das Projektmanagement in der AEC-Branche zu vereinfachen und zu beschleunigen. Sie integriert eine Reihe von fortschrittlichen Tools zur Optimierung von Arbeitsabläufen und zur Verbesserung der Produktivität, von der Projektverfolgung und Aufgabenverwaltung bis hin zu automatisierten Prüfungen und Machbarkeitsbewertungen. Unsere Web-App ermöglicht es Teams, den Fortschritt zu verfolgen, nahtlos zusammenzuarbeiten und datengestützte Entscheidungen schneller als je zuvor zu treffen. Die App umfasst auch anspruchsvolle Funktionen wie automatisierte Plausibilitätsmodellierung basierend auf dem Standort und die Erstellung neuer Geometrien zur Visualisierung nachhaltiger Baupraktiken.",
        start_solutionsIntro: "Maßgeschneiderte digitale Lösungen für AEC-Exzellenz: Optimierung von Arbeitsabläufen, Automatisierung von Aufgaben und Verbesserung der Visualisierung mit benutzerdefinierten Tools für Architektur-, Ingenieur- und Bauprofis.",
        start_solutionsText: "Bei Non-Plan bauen wir nicht nur Tools - wir schaffen Lösungen, die sich den einzigartigen Herausforderungen der AEC-Branche stellen. Egal, ob Sie in der Architektur, im Ingenieurwesen oder im Bauwesen tätig sind, unsere Dienstleistungen können Ihnen helfen, Ihre Prozesse zu optimieren. Wir bieten:",
        start_solutionsList1:"• Benutzerdefinierte Webanwendungen, die in Ihre bestehenden Arbeitsabläufe integriert werden.",
        start_solutionsList2:"• Grasshopper- und Python-Automatisierungsskripte zur Optimierung sich wiederholender Aufgaben.",
        start_solutionsList3:"• Fortgeschrittene BIM- und CAD-Beratung zur Erstellung und Verwaltung intelligenter Gebäudemodelle.",
        start_solutionsList4:"• Spezialisierte AR-Tools zur Visualisierung von Entwürfen und Daten in immersiven Umgebungen.",
        start_whoTitle: "Wer wir sind",
        start_whoText: "non-plan ist ein Team von Architekten, Designern und Innovatoren, die sich der Neugestaltung der AEC-Branche durch digitale Transformation und kreative Zusammenarbeit verschrieben haben. Unser kollektives Fachwissen überbrückt die Kluft zwischen traditioneller architektonischer Praxis und modernster Technologie und fördert eine Kultur der Experimentierfreude und Innovation.",
        start_projectsTitle: "Projekte und Kooperationen",
        start_projectsText: "non-plan ist ein Team von Architekten, Designern und Innovatoren, die sich der Neugestaltung der AEC-Branche durch digitale Transformation und kreative Zusammenarbeit verschrieben haben. Unser kollektives Fachwissen überbrückt die Kluft zwischen traditioneller architektonischer Praxis und modernster Technologie und fördert eine Kultur der Experimentierfreude und Innovation.",
        start_accessTitle: "Zugriff auf die non-plan Plattform",
        start_accessText: "Nutzen Sie das volle Potenzial Ihrer Projekte mit der non-plan WebApp. Unsere Plattform bietet eine Vielzahl von Funktionen zur Optimierung Ihres Projektmanagements, Automatisierung von Arbeitsabläufen und Erstellung nachhaltiger设计lösungen. Egal, ob Sie Projektmanager, Architekt, Auftragnehmer oder Entwickler sind, unsere Webanwendung kann Ihnen helfen, Ihre Arbeitsprozesse zu optimieren und fundierte Entscheidungen zu treffen.",
        start_logIn: "Anmelden bei der Non-Plan-Plattform",
        start_loginWelcome1: "Willkommen",
        start_loginWelcome2: "Anmelden bei der non-plan Plattform",
        start_forgotPassword: "Passwort vergessen?",
        start_continue: "Fortfahren",
        start_newAccount: "Haben Sie noch kein Konto?",
        start_UsernameEmail: "Benutzername oder E-Mail-Adresse",
        start_Password: "Passwort",
        start_Collaborations: "Wir haben stolz mit den folgenden Unternehmen und öffentlichen Institutionen zusammengearbeitet und wirkungsvolle Lösungen geliefert",
        start_Collaborations2: "Diese Kooperationen unterstreichen unser Engagement für die Verbindung von Innovation und Nachhaltigkeit in der AEC-Branche.",
        start_innovateText2:"Maßgeschneiderte digitale Lösungen für AEC-Exzellenz: Optimierung von Arbeitsabläufen, Automatisierung von Aufgaben und Verbesserung der Visualisierung mit benutzerdefinierten Tools für Architektur-, Ingenieur- und Bauprofis.(Foto von Marta Buso)",
        start_AR:"Augmented Reality",
        start_AREngie:"Engie Habegger Projekt: Swissbau 2022 AR-Erlebnis.",
        start_ARLiechtenstein:"Universität Liechtenstein Biennale App: Hervorhebung der E-Schrott-Verbindungen zwischen Liechtenstein und Ghana.Universität Liechtenstein Biennale App: Hervorhebung der E-Schrott-Verbindungen zwischen Liechtenstein und Ghana.(Foto von Marta Buso)",
        start_Hohrainli: "Parametrische Studie zur effizienten Positionierung wiederverwendbarer Fassadenelemente, erstellt mit Grasshopper/Python für das Forschungsprojekt GartenPark Hohrainli des Instituts für Umwelt und natürliche Ressourcen an der ZHAW.",
        start_Generator: "Parametrische Studie zur Erstellung eines Kompatibilitätsprogramms, das verschiedene Räume integriert, inspiriert von Cedric Price und präsentiert an der HSLU Luzern.",
        start_GIS: "GIS-Importer für Archicad: Ein Grasshopper-Skript, das von OOS beauftragt wurde und GIS-Daten, einschließlich Topografie und Materialien, einliest und 3D-Landschaftselemente in Archicad importiert, sie nach Material trennt und Gebäude einfügt.",
        start_Shade: "Schattenüberlappungsrechner für Grasshopper: Ein Skript, das von OOS beauftragt wurde und überlappende Schatten über einen Zeitraum von 3 Stunden berechnet, gemäß den Vorschriften des Kantons Zürich.",
        start_PythonMat: "Materialraum-Tags für Archicad: Ein Python-Skript, das von OOS beauftragt wurde und Raumtags für Materialien direkt in Archicad automatisiert.",
        start_Chaos: "Kreischaos, eine Anwendung zum Ersetzen von Geometrien aus wiederverwendbaren Elementlisten",
        start_ServicesTitle: "Dienstleistungen",
        start_service1Titel:"Plugin-Entwicklung",
        start_service2Titel:"Webanwendungen",
        start_service3Titel:"VR/AR-Apps",
        start_service4Titel:"BIM-Beratung",
        start_service1Content: "Wir sind spezialisiert auf die Erstellung maßgeschneiderter Plugins für Tools wie Archicad, Rhinoceros und Grasshopper, um den einzigartigen Bedürfnissen der AEC-Branche gerecht zu werden. Durch enge Zusammenarbeit mit den Kunden identifizieren wir Engpässe und Ineffizienzen und entwickeln dann maßgeschneiderte Lösungen, die sich nahtlos in bestehende Arbeitsabläufe integrieren. Unsere Plugins erweitern die Funktionalität, optimieren sich wiederholende Aufgaben und lösen komplexe Herausforderungen, sodass Ihre Tools leistungsfähiger, anpassungsfähiger und effizienter im Umgang mit komplexen Design- und Ingenieurprojekten werden.",
        start_service2Content: "Wir entwerfen und erstellen benutzerdefinierte Anwendungen, die es Teams ermöglichen, intelligenter und nicht härter zu arbeiten. Durch die Übersetzung komplexer Prozesse in benutzerfreundliche Schnittstellen ermöglichen wir Ihnen den jederzeitigen Zugriff auf Ihre Modelle, Daten und Tools, egal wo Sie sich befinden. Unsere Lösungen sind kollaborativ, skalierbar und nahtlos in Ihre Arbeitsabläufe integriert, wodurch Projektmanagement, Datenvisualisierung und Teamkommunikation effizienter gestaltet werden. Wir verwandeln Ihre digitale Plattform in eine, die die Produktivität steigert und alle Beteiligten auf dem Laufenden hält.",
        start_service3Content: "Nutzen Sie die Möglichkeiten der virtuellen und erweiterten Realität, um Ihre Entwürfe und Präsentationen zu verbessern. Mit Unity entwickeln wir immersive Apps, die es Ihnen ermöglichen, Ihre Modelle in Echtzeit zu visualisieren, mit ihnen zu interagieren und sie zu verfeinern. Egal, ob Sie Materialien erkunden, Designvariationen testen oder Ideen Kunden präsentieren möchten, unsere VR/AR-Lösungen ermöglichen es Ihnen, fundierte Entscheidungen mit Vertrauen zu treffen. Wir konzentrieren uns darauf, intuitive, wirkungsvolle Erlebnisse zu schaffen, die Ihre Projekte zum Leben erwecken und eine bessere Kommunikation und Verständigung fördern.",
        start_service4Content: "Mit jahrelanger Erfahrung in der Lehre und der Zusammenarbeit mit führenden Architekturunternehmen bieten wir umfassende BIM-Beratung Dienstleistungen an. Von der Optimierung von Arbeitsabläufen bis zur Implementierung fortschrittlicher Modellierungsstrategien, die maßgeschneidert für Ihr Unternehmen sind, helfen wir Ihnen, das volle Potenzial der BIM-Technologie auszuschöpfen. Unser Fachwissen stellt sicher, dass Ihre Projekte effizienter, mit weniger Fehlern und besserer Koordination zwischen den Teams durchgeführt werden. Egal, ob Sie BIM zum ersten Mal einführen oder Ihre bestehenden Prozesse verfeinern möchten, wir bieten die Anleitung und die Werkzeuge, die Sie zum Erfolg benötigen.",
        start_npInfoSoon: "Weitere Informationen demnächst verfügbar...",
        start_Mbuso_credit: "Foto von Marta Buso",
        start_OOS_credit: "Skript für das Projekt 'Josef will wohnen', geschrieben für OOS",
        sidebar_projects: "Projekte",
        sidebar_users: "Benutzer",
        sidebar_dashboard: "Dashboard",
        sidebar_tasks: "Aufgaben",
        sidebar_calendar: "Kalender",
        sidebar_documents: "Dokumente",
        sidebar_tools: "Werkzeuge",
        projects_status: "Status",
        projects_role: "Rolle",
        projects_cost: "Kosten",
        projects_progress: "Fortschritt",
        projects_new: "Neues Projekt",
        projects_name: "Name",
        projects_name_placeholder: "Wie heißt Ihr Projekt?",
        projects_name_tip: "TIPP: Geben Sie einen kurzen Namen an",
        projects_description: "Beschreibung",
        projects_description_placeholder: "Geben Sie Ihrem Projekt eine schöne Beschreibung!",
        projects_location: "Standort",
        projects_location_placeholder: "Wo befindet sich Ihr Projekt?",
        projects_cost_placeholder: "Wie hoch sind die geschätzten Kosten des Projekts?",
        projects_cost_tip: "Geschätzte Kosten des Projekts",
        projects_progress_placeholder: "Wie hoch ist der geschätzte Fertigstellungsgrad des Projekts?",
        projects_progress_tip: "Geschätzter Fortschrittsprozentsatz des Projekts",
        projects_role_not_defined: "nicht definiert",
        projects_role_architect: "Architekt",
        projects_role_engineer: "Ingenieur",
        projects_role_developer: "Entwickler",
        projects_status_pending: "Ausstehend",
        projects_status_active: "Aktiv",
        projects_status_finished: "Abgeschlossen",
        projects_status_onhold: "Zurückgestellt",
        projects_phase: "Planungsphase",
        projects_phase_design: "Entwurf",
        projects_phase_construction_project: "Bauprojekt",
        projects_phase_execution: "Ausführung",
        projects_phase_construction: "Bau",
        projects_start_date: "Startdatum",
        projects_finish_date: "Enddatum",
        projects_cancel: "Abbrechen",
        projects_accept: "Akzeptieren",
        projects_error: "Fehler",
        projects_confirm_delete_task: "Möchten Sie die Aufgabe wirklich löschen:",
        projects_confirm_delete_user: "Möchten Sie den Benutzer wirklich löschen",
        projects_no_description: "Keine Beschreibung vorhanden.",
        projects_no_status: "Kein Status vorhanden.",
        projects_no_cost: "Keine Kostenangabe vorhanden.",
        projects_no_role: "Keine Rolle vorhanden.",
        projects_no_start_date: "Kein Startdatum vorhanden.",
        projects_no_finish_date: "Kein Enddatum vorhanden.",
        projects_no_users_assigned: "Keine Benutzer diesem Projekt zugewiesen.",
        projects_no_todos: "Keine Aufgaben für dieses Projekt.",
        projects_search_todos: "Aufgaben nach Name suchen",
        projects_assigned_users: "Zugewiesene Benutzer",
        projects_todo: "Aufgaben",
        projects_show_todo: "Aufgaben anzeigen",
        projects_show_assigned_users: "Zugewiesene Benutzer anzeigen",
        projects_remove_user: "Benutzer aus Projekt entfernen",
        projects_unknown_user: "Unbekannter Benutzer",
        projects_add_task: "Aufgabe hinzufügen",
        projects_edit_task: "Aufgabe bearbeiten",
        projects_tip_short_title: "TIPP: Geben Sie einen kurzen Titel an",
        projects_priority: "Priorität",
        projects_priority_high: "Hoch",
        projects_priority_standard: "Standard",
        projects_priority_low: "Niedrig",
        projects_estimated_hours: "Geschätzte Stunden",
        projects_estimated_hours_placeholder: "Geschätzte Stunden für die Aufgabe",
        projects_estimated_hours_tip: "Geschätzte Stunden für die Aufgabe",
        projects_actual_hours: "Tatsächliche Stunden",
        projects_actual_hours_placeholder: "Bisher verwendete Stunden",
        projects_actual_hours_tip: "Bisher verwendete Stunden",
        projects_responsible_person: "Verantwortliche Person",
        projects_select_responsible: "Verantwortliche Person auswählen",
        projects_created_by: "Erstellt von",
        projects_select_creator: "Ersteller auswählen",
        projects_due_date: "Fälligkeitsdatum",
        projects_dependencies: "Abhängigkeiten",
        projects_dependencies_tip: "Kommagetrennte Aufgaben-IDs",
        projects_comments: "Kommentare",
        projects_comments_placeholder: "Fügen Sie einen erläuternden Kommentar hinzu",
        projects_edit_project: "Projekt bearbeiten",
        projects_role_in_project: "Rolle in diesem Projekt",
        projects_role_placeholder: "z.B. Projektleiter, Berater...",
        projects_assign_user: "Benutzer dem Projekt zuweisen",
        projects_user: "Benutzer",
        projects_select_user: "Benutzer auswählen",
        projects_assign: "Zuweisen",
        projects_change: "Ändern",
        projects_delete: "Löschen",
        users_new_user: "Neuer Benutzer",
        users_change_user: "Benutzer ändern",
        users_name: "Vorname",
        users_surname: "Nachname",
        users_email: "E-Mail-Adresse",
        users_phone: "Telefonnummer",
        users_role: "Rolle",
        users_access: "Zugriffsrechte",
        users_access_admin: "Administrator",
        users_access_editor: "Editor",
        users_access_guest: "Gast",
        users_company: "Firma",
        users_select_company: "Firma auswählen",
        users_new_company: "Neue Firma",
        users_company_name: "Firmenname",
        users_company_address: "Firmenadresse",
        users_company_email: "Kontakt E-Mail",
        users_company_phone: "Telefonnummer",
        users_edit_company: "Firma bearbeiten",
        users_confirm_delete_user: "Möchten Sie den Benutzer wirklich löschen",
        users_confirm_delete_company: "Möchten Sie die Firma wirklich löschen",
        users_delete: "Löschen",
        users_delete_user: "Benutzer löschen",
        users_delete_company: "Firma löschen",
        users_total_number: "Gesamtanzahl der",
        users_companies: "Firmen",
        users_user_name: "Benutzername",
        users_show_companies: "Firmen anzeigen",
        users_show_users: "Benutzer anzeigen",
    },
    es: {
        //Header:
        en: "EN",
        de: "DE",
        projects_title: "Título",
        projects_all_projects: "Todos los proyectos",
        search_projects: "Buscar proyectos",
        search_users: "Buscar usuarios",
        search_tasks: "Buscar tareas",
        search_companies: "Buscar empresas",
        //start_non-plan Website:
        start_welcome: "Bienvenido a non-plan",
        start_innovateHeading: "Transformando la industria AEC con innovación: Descubre cómo generamos impacto",
        start_innovateText: "Soluciones digitales a medida para la excelencia en AEC: optimizando flujos de trabajo, automatizando tareas y mejorando la visualización con herramientas personalizadas para profesionales de arquitectura, ingeniería y construcción",
        start_introPlatform: "Simplifica la gestión AEC con la plataforma Non-Plan: Próximamente, esta app optimizará flujos de trabajo, seguimiento de proyectos y visualizará soluciones sostenibles, todo en un solo lugar.",
        start_platformText: "La WebApp Non-Plan está diseñada para simplificar y acelerar la gestión de proyectos en la industria AEC. Integra herramientas avanzadas para optimizar flujos de trabajo y mejorar la productividad, desde el seguimiento de proyectos y tareas hasta comprobaciones automáticas y evaluaciones de viabilidad. Nuestra app permite a los equipos seguir el progreso, colaborar y tomar decisiones basadas en datos más rápido que nunca. También incluye capacidades como modelado de plausibilidad automatizado según la ubicación y generación de nuevas geometrías para visualizar prácticas sostenibles.",
        start_solutionsIntro: "Soluciones digitales a medida para la excelencia en AEC: optimizando flujos de trabajo, automatizando tareas y mejorando la visualización con herramientas personalizadas para profesionales de arquitectura, ingeniería y construcción.",
        start_solutionsText: "En Non-Plan no solo creamos herramientas, creamos soluciones que abordan los desafíos únicos de la industria AEC. Ya sea en arquitectura, ingeniería o construcción, nuestros servicios pueden optimizar tus procesos. Ofrecemos:",
        start_solutionsList1: "• Aplicaciones web personalizadas que se integran en tus flujos de trabajo existentes.",
        start_solutionsList2: "• Scripts de automatización en Grasshopper y Python para agilizar tareas repetitivas.",
        start_solutionsList3: "• Consultoría avanzada en BIM y CAD para crear y gestionar modelos inteligentes de edificios.",
        start_solutionsList4: "• Herramientas AR especializadas para visualizar diseños y datos en entornos inmersivos.",
        start_whoTitle: "Quiénes somos",
        start_whoText: "non-plan es un equipo de arquitectos, diseñadores e innovadores dedicados a redefinir la industria AEC mediante la transformación digital y la colaboración creativa. Nuestra experiencia colectiva une la práctica arquitectónica tradicional con la tecnología de vanguardia, fomentando una cultura de experimentación e innovación.",
        start_projectsTitle: "Proyectos y colaboraciones",
        start_projectsText: "non-plan es un equipo de arquitectos, diseñadores e innovadores dedicados a redefinir la industria AEC mediante la transformación digital y la colaboración creativa. Nuestra experiencia colectiva une la práctica arquitectónica tradicional con la tecnología de vanguardia, fomentando una cultura de experimentación e innovación.",
        start_accessTitle: "Accede a la plataforma non-plan",
        start_accessText: "Desbloquea el potencial de tus proyectos con la WebApp non-plan. Nuestra plataforma ofrece funciones para optimizar la gestión de proyectos, automatizar flujos de trabajo y generar soluciones de diseño sostenible. Ya seas gestor, arquitecto, contratista o desarrollador, nuestra app te ayuda a optimizar procesos y tomar decisiones informadas.",
        start_logIn: "Iniciar sesión en la plataforma Non-Plan",
        start_loginWelcome1: "Bienvenido",
        start_loginWelcome2: "Inicia sesión en la plataforma non-plan",
        start_forgotPassword: "¿Olvidaste tu contraseña?",
        start_continue: "Continuar",
        start_newAccount: "¿No tienes una cuenta?",
        start_UsernameEmail: "Nombre de usuario o correo electrónico",
        start_Password: "Contraseña",
        start_Collaborations: "Hemos colaborado con las siguientes empresas e instituciones públicas, entregando soluciones de impacto",
        start_Collaborations2: "Estas colaboraciones demuestran nuestro compromiso con la innovación y la sostenibilidad en la industria AEC.",
        start_innovateText2: "Soluciones digitales a medida para la excelencia en AEC: optimizando flujos de trabajo, automatizando tareas y mejorando la visualización con herramientas personalizadas para profesionales de arquitectura, ingeniería y construcción. (Foto de Marta Buso)",
        start_AR: "Realidad aumentada",
        start_AREngie: "Proyecto Engie Habegger: experiencia AR en Swissbau 2022.",
        start_ARLiechtenstein: "App Bienal Universidad de Liechtenstein: destacando conexiones de residuos electrónicos entre Liechtenstein y Ghana. (Foto de Marta Buso)",
        start_Hohrainli: "Estudio paramétrico para la colocación eficiente de elementos de fachada reutilizados, creado con Grasshopper/Python para el proyecto de investigación GartenPark Hohrainli del Instituto de Medio Ambiente y Recursos Naturales de ZHAW.",
        start_Generator: "Estudio paramétrico para generar un programa de compatibilidad que integre diferentes espacios, inspirado en Cedric Price y presentado en HSLU Lucerna.",
        start_GIS: "Importador GIS para Archicad: Script de Grasshopper encargado por OOS que lee datos GIS, incluyendo topografía y materiales, e importa elementos de paisaje 3D en Archicad, separándolos por material e incluyendo edificios.",
        start_Shade: "Calculadora de superposición de sombras para Grasshopper: Script encargado por OOS que calcula sombras superpuestas durante 3 horas, según la normativa de Zúrich.",
        start_PythonMat: "Etiquetas de materiales para Archicad: Script Python encargado por OOS que automatiza etiquetas de materiales en Archicad.",
        start_Chaos: "Circular Chaos, una aplicación para reemplazar geometrías de listas de elementos reutilizables",
        start_ServicesTitle: "Servicios",
        start_service1Titel: "Desarrollo de plugins",
        start_service2Titel: "Aplicaciones web",
        start_service3Titel: "Apps VR/AR",
        start_service4Titel: "Consultoría BIM",
        start_service1Content: "Nos especializamos en crear plugins a medida para herramientas como Archicad, Rhinoceros y Grasshopper, adaptados a las necesidades de la industria AEC. Colaboramos estrechamente con los clientes para identificar cuellos de botella y crear soluciones personalizadas que se integran en los flujos de trabajo existentes. Nuestros plugins mejoran la funcionalidad, automatizan tareas repetitivas y resuelven desafíos complejos, haciendo tus herramientas más potentes y eficientes.",
        start_service2Content: "Diseñamos y desarrollamos aplicaciones personalizadas que permiten a los equipos trabajar de forma más inteligente. Traducimos procesos complejos en interfaces intuitivas para que accedas a tus modelos, datos y herramientas en cualquier momento y lugar. Nuestras soluciones son colaborativas, escalables y se adaptan a tus flujos de trabajo, mejorando la gestión de proyectos, la visualización de datos y la comunicación del equipo.",
        start_service3Content: "Aprovecha la realidad virtual y aumentada para mejorar tus diseños y presentaciones. Usando Unity, desarrollamos apps inmersivas que te permiten visualizar, interactuar y refinar tus modelos en tiempo real. Ya sea explorando materiales, probando variantes o presentando ideas a clientes, nuestras soluciones VR/AR te ayudan a tomar decisiones informadas. Creamos experiencias intuitivas e impactantes que dan vida a tus proyectos y mejoran la comunicación.",
        start_service4Content: "Con años de experiencia en docencia y colaboración con estudios líderes, ofrecemos consultoría BIM integral. Desde optimizar flujos de trabajo hasta implementar estrategias avanzadas de modelado, te ayudamos a aprovechar al máximo la tecnología BIM. Nuestra experiencia garantiza proyectos más eficientes, con menos errores y mejor coordinación. Ya sea que adoptes BIM por primera vez o mejores procesos existentes, te damos la guía y herramientas para el éxito.",
        start_npInfoSoon: "más información próximamente...",
        projects_status: "Estado",
        projects_role: "Rol",
        projects_cost: "Costo",
        projects_progress: "Progreso",
        projects_new: "Nuevo Proyecto",
        projects_name: "Nombre",
        projects_name_placeholder: "¿Cómo se llama tu proyecto?",
        projects_name_tip: "CONSEJO: ponle un nombre corto",
        projects_description: "Descripción",
        projects_description_placeholder: "¡Dale una buena descripción a tu proyecto!",
        projects_location: "Ubicación",
        projects_location_placeholder: "¿Dónde está ubicado tu proyecto?",
        projects_cost_placeholder: "¿Cuál es el costo estimado del proyecto?",
        projects_cost_tip: "Costo estimado del proyecto",
        projects_progress_placeholder: "¿Cuál es el progreso estimado de finalización del proyecto?",
        projects_progress_tip: "Porcentaje estimado de progreso del proyecto",
        projects_role_not_defined: "no definido",
        projects_role_architect: "Arquitecto",
        projects_role_engineer: "Ingeniero",
        projects_role_developer: "Desarrollador",
        projects_status_pending: "Pendiente",
        projects_status_active: "Activo",
        projects_status_finished: "Finalizado",
        projects_status_onhold: "En espera",
        projects_phase: "Fase de diseño",
        projects_phase_design: "Diseño",
        projects_phase_construction_project: "Proyecto de construcción",
        projects_phase_execution: "Ejecución",
        projects_phase_construction: "Construcción",
        projects_start_date: "Fecha de inicio",
        projects_finish_date: "Fecha de finalización",
        projects_cancel: "Cancelar",
        projects_accept: "Aceptar",
        projects_error: "Error",
        projects_confirm_delete_task: "¿Seguro que quieres eliminar la tarea:",
        projects_confirm_delete_user: "¿Seguro que quieres eliminar el usuario",
        projects_no_description: "No hay descripción.",
        projects_no_status: "No hay estado.",
        projects_no_cost: "No hay costo.",
        projects_no_role: "No hay rol.",
        projects_no_start_date: "No hay fecha de inicio.",
        projects_no_finish_date: "No hay fecha de finalización.",
        projects_no_users_assigned: "No hay usuarios asignados a este proyecto.",
        projects_no_todos: "No hay tareas para este proyecto.",
        projects_search_todos: "Buscar tareas por nombre",
        projects_assigned_users: "Usuarios asignados",
        projects_todo: "Tareas",
        projects_show_todo: "Mostrar tareas",
        projects_show_assigned_users: "Mostrar usuarios asignados",
        projects_remove_user: "Eliminar usuario del proyecto",
        projects_unknown_user: "Usuario desconocido",
        projects_add_task: "Agregar tarea",
        projects_edit_task: "Editar tarea",
        projects_tip_short_title: "CONSEJO: ponle un título corto",
        projects_priority: "Prioridad",
        projects_priority_high: "Alta",
        projects_priority_standard: "Estándar",
        projects_priority_low: "Baja",
        projects_estimated_hours: "Horas estimadas",
        projects_estimated_hours_placeholder: "Horas estimadas para la tarea",
        projects_estimated_hours_tip: "Horas estimadas para la tarea",
        projects_actual_hours: "Horas reales",
        projects_actual_hours_placeholder: "Horas usadas hasta ahora",
        projects_actual_hours_tip: "Horas usadas hasta ahora",
        projects_responsible_person: "Persona responsable",
        projects_select_responsible: "Seleccione persona responsable",
        projects_created_by: "Creado por",
        projects_select_creator: "Seleccione creador",
        projects_due_date: "Fecha de vencimiento",
        projects_dependencies: "Dependencias",
        projects_dependencies_tip: "IDs de tareas separadas por comas",
        projects_comments: "Comentarios",
        projects_comments_placeholder: "Agregue cualquier comentario aclaratorio",
        projects_edit_project: "Editar proyecto",
        projects_role_in_project: "Rol en este proyecto",
        projects_role_placeholder: "p. ej. Líder de proyecto, Consultor...",
        projects_assign_user: "Asignar usuario al proyecto",
        projects_user: "Usuario",
        projects_select_user: "Seleccione usuario",
        projects_assign: "Asignar",
        projects_change: "Cambiar",
        projects_delete: "Eliminar",
        // Sidebar and user/company management (added missing Spanish translations)
        sidebar_projects: "Proyectos",
        sidebar_users: "Usuarios",
        sidebar_dashboard: "Panel",
        sidebar_tasks: "Tareas",
        sidebar_calendar: "Calendario",
        sidebar_documents: "Documentos",
        sidebar_tools: "Herramientas",
    },
};
