// Language translations
export const translations = {
    en: {
        //Header:
        en: "EN",
        de: "DE",
        services: "services",
        insights: "insights",
        //start_non-plan Website:
        start_welcome: "Welcome to non-plan",
        start_innovateHeading: "Transforming the AEC Industry with Innovation: Discover How We Make an Impact",
        start_innovateText: "Tailor-Made Digital Solutions for AEC Excellence: Streamlining Workflows, Automating Tasks, and Enhancing Visualization with Custom Tools for Architecture, Engineering, and Construction Professionals",
        start_introPlatform: "Simplify AEC Management with the Non-Plan Platform: Coming soon, this app will streamline workflows, track projects, and visualize sustainable solutions—all in one place.",
        start_platformText: "The Non-Plan WebApp is designed to simplify and accelerate project management in the AEC industry. It integrates a range of advanced tools to streamline workflows and improve productivity, from project tracking and task management to automated checks and feasibility assessments. Our web app empowers teams to track progress, collaborate seamlessly, and make data-driven decisions faster than ever before. The app also includes sophisticated capabilities such as automated plausibility modeling based on location and the generation of new geometries to visualize sustainable building practices.",
        start_solutionsIntro: "Tailor-Made Digital Solutions for AEC Excellence: Streamlining Workflows, Automating Tasks, and Enhancing Visualization with Custom Tools for Architecture, Engineering, and Construction Professionals.",
        start_solutionsText: "At Non-Plan, we don't just build tools – we create solutions that address the unique challenges of the AEC industry. Whether you're working in architecture, engineering, or construction, our services can help optimize your processes. We offer:",
        start_solutionsList1:"• Custom web applications that integrate into your existing workflows.",
        start_solutionsList2:"• Grasshopper and Python automation scripts to streamline repetitive tasks.",
        start_solutionsList3:"• Advanced BIM and CAD consulting for creating and managing intelligent building models.",
        start_solutionsList4:"• Specialized AR tools for visualizing designs and data in immersive environments.",
        start_whoTitle: "Who We Are",
        start_whoText: "non-plan is a team of architects, designers, and innovators dedicated to redefining the AEC industry through digital transformation and creative collaboration.Our collective expertise bridges the gap between traditional architectural practice and cutting-edge technology, fostering a culture of experimentation and innovation.",
        start_projectsTitle: "Projects and Collaborations",
        start_projectsText: "non-plan is a team of architects, designers, and innovators dedicated to redefining the AEC industry through digital transformation and creative collaboration.Our collective expertise bridges the gap between traditional architectural practice and cutting-edge technology, fostering a culture of experimentation and innovation.",
        start_accessTitle: "Access the non-plan Platform",
        start_accessText: "Unlock the full potential of your projects with the non-plan WebApp. Our platform offers a wide range of features to streamline your project management, automate workflows, and generate sustainable design solutions. Whether you're a project manager, architect, contractor, or developer, our web application can help you optimize your work processes and make informed decisions.",
        start_logIn: "Log in to Non-Plan Platform",
        start_loginWelcome1: "Welcome",
        start_loginWelcome2: "Login to the non-plan Platform",
        start_forgotPassword: "Forgot your password?",
        start_continue: "Continue",
        start_newAccount: "Don't have an account?",
        start_UsernameEmail: "Username or email address",
        start_Password: "Password",
        start_Collaborations: "We have proudly worked with the following companies and public institutions , delivering impactful solutions",
        start_Collaborations2: "These collaborations highlight our commitment to bridging innovation and sustainability within the AEC industry.",
        start_innovateText2:"Tailor-Made Digital Solutions for AEC Excellence: Streamlining Workflows, Automating Tasks, and Enhancing Visualization with Custom Tools for Architecture, Engineering, and Construction Professionals.(Photo by Marta Buso)",
        start_AR:"Augmented Reality",
        start_AREngie:"Engie Habegger Project: Swissbau 2022 AR experience.",
        start_ARLiechtenstein:"University of Liechtenstein Biennale App: Highlighting e-waste connections between Liechtenstein and Ghana.University of Liechtenstein Biennale App: Highlighting e-waste connections between Liechtenstein and Ghana.(Photo by Marta Buso)",
        start_Hohrainli: "Parametric study for the efficient positioning of reused facade elements, created using Grasshopper/Python for the research project GartenPark Hohrainli by the Institute for Environment and Natural Resources at ZHAW.",
        start_Generator: "Parametric study for generating a compatibility program that integrates different spaces, inspired by Cedric Price and presented at HSLU Luzern.",
        start_GIS: "GIS Importer for Archicad: A Grasshopper script commissioned by OOS that reads GIS data, including topography and materials, and imports 3D landscape elements into Archicad, separating them by material and including buildings.",
        start_Shade: "Shadow Overlap Calculator for Grasshopper: A script commissioned by OOS that calculates overlapping shadows over a 3-hour period, in accordance with Kanton Zurich regulations.",
        start_PythonMat: "Material Room Tags for Archicad: A Python script commissioned by OOS that automates room tags for materials directly within Archicad.",
        start_Chaos: "Circular Chaos, an application to replace geometries from reusable element lists",
        start_ServicesTitle: "Services",
        start_service1Titel:"Plugin Development",
        start_service2Titel:"Web Applications",
        start_service3Titel:"VR/AR Apps",
        start_service4Titel:"BIM Consulting",
        start_service1Content: "We specialize in creating bespoke plugins for tools like Archicad, Rhinoceros, and Grasshopper to cater to the unique needs of the AEC industry. By closely collaborating with clients, we identify bottlenecks and inefficiencies, then craft custom solutions that seamlessly integrate into existing workflows. Our plugins enhance functionality, streamline repetitive tasks, and solve complex challenges, ensuring your tools are more powerful, adaptable, and efficient in handling intricate design and engineering projects.",
        start_service2Content: "We design and build custom applications that empower teams to work smarter, not harder. By translating complex processes into user-friendly interfaces, we enable you to access your models, data, and tools anytime, anywhere. Our solutions are collaborative, scalable, and tailored to fit seamlessly into your workflows, making project management, data visualization, and team communication more efficient. We transform your digital platform into one that boosts productivity and keeps everyone aligned.",
        start_service3Content: "Harness the power of virtual and augmented reality to elevate your designs and presentations. Using Unity, we develop immersive apps that allow you to visualize, interact with, and refine your models in real time. Whether you’re exploring materials, testing design variations, or showcasing ideas to clients, our VR/AR solutions enable you to make informed decisions with confidence. We focus on creating intuitive, impactful experiences that bring your projects to life and facilitate better communication and understanding.",
        start_service4Content: "With years of experience teaching and working with leading architecture firms, we  provide comprehensive BIM consulting services. From optimizing  workflows to implementing advanced modeling strategies tailor-made for your company, we help you unlock the full potential of BIM technology. Our expertise ensures your  projects are delivered more efficiently, with fewer errors and better coordination across teams. Whether you’re adopting BIM for the first  time or refining your existing processes, we provide the guidance and  tools you need to succeed.",
        start_npInfoSoon: "more information coming soon...",
        start_Mbuso_credit: "Photo by Marta Buso",
        start_OOS_credit: "Script for the 'Josef will wohnen' project, written for OOS",

    },
    de: {
        //Header:
        en: "EN",
        de: "DE",
        services: "services",
        insights: "insights",
        //start_non-plan Website:
        start_welcome: "Willkommen bei non-plan",
        start_innovateHeading: "Innovation für die AEC-Branche: Erfahren Sie, wie wir einen Unterschied machen",
        start_innovateText: "Massgeschneiderte digitale Lösungen für Spitzenleistungen im AEC-Bereich: Workflows optimieren, Aufgaben automatisieren und Visualisierung verbessern mit individuellen Tools für Architektur-, Ingenieur- und Bauprofis.",
        start_introPlatform: "AEC-Management mit der Non-Plan-Plattform vereinfachen: Diese App wird bald verfügbar sein und Workflows optimieren, Projekte verfolgen und nachhaltige Lösungen visualisieren – alles an einem Ort.",
        start_platformText: "Die Non-Plan WebApp ist darauf ausgelegt, Projektmanagement in der AEC-Branche zu vereinfachen und zu beschleunigen. Sie integriert fortschrittliche Tools, um Workflows zu optimieren und die Produktivität zu steigern – von der Projektverfolgung und Aufgabenverwaltung bis hin zu automatisierten Prüfungen und Machbarkeitsanalysen. Mit unserer WebApp können Teams Fortschritte verfolgen, nahtlos zusammenarbeiten und datenbasierte Entscheidungen schneller treffen. Ausserdem bietet die App Funktionen wie automatisierte Plausibilitätsmodelle basierend auf Standorten sowie die Generierung neuer Geometrien zur Visualisierung nachhaltiger Baupraktiken.",
        start_solutionsIntro: "Massgeschneiderte digitale Lösungen für Spitzenleistungen im AEC-Bereich: Workflows optimieren, Aufgaben automatisieren und Visualisierung verbessern mit individuellen Tools für Architektur-, Ingenieur- und Bauprofis.",
        start_solutionsText: "Bei Non-Plan entwickeln wir nicht nur Tools – wir schaffen Lösungen, die auf die einzigartigen Herausforderungen der AEC-Branche zugeschnitten sind. Egal ob Architektur, Ingenieurwesen oder Bauwesen, unsere Services helfen, Ihre Prozesse zu optimieren. Wir bieten:",
        start_solutionsList1: "• Individuelle Webanwendungen, die in bestehende Workflows integriert werden können.",
        start_solutionsList2: "• Grasshopper- und Python-Automatisierungsskripte zur Vereinfachung repetitiver Aufgaben.",
        start_solutionsList3: "• Fortgeschrittene BIM- und CAD-Beratung zur Erstellung und Verwaltung intelligenter Gebäudemodelle.",
        start_solutionsList4: "• Spezialisierte AR-Tools zur Visualisierung von Designs und Daten in immersiven Umgebungen.",
        start_whoTitle: "Wer wir sind",
        start_whoText: "non-plan ist ein Team aus Architekten, Designern und Innovatoren, das sich der digitalen Transformation und kreativen Zusammenarbeit verschrieben hat. Unsere gebündelte Expertise überbrückt die Kluft zwischen traditioneller Architektur und modernster Technologie, fördert eine Kultur der Experimentation und Innovation.",
        start_projectsTitle: "Projekte und Kooperationen",
        start_projectsText: "non-plan ist ein Team aus Architekten, Designern und Innovatoren, das sich der digitalen Transformation und kreativen Zusammenarbeit verschrieben hat. Unsere gebündelte Expertise überbrückt die Kluft zwischen traditioneller Architektur und modernster Technologie, fördert eine Kultur der Experimentation und Innovation.",
        start_accessTitle: "Zugang zur Non-Plan-Plattform",
        start_accessText: "Entfalten Sie das volle Potenzial Ihrer Projekte mit der Non-Plan WebApp. Unsere Plattform bietet eine Vielzahl von Funktionen, um Ihr Projektmanagement zu optimieren, Workflows zu automatisieren und nachhaltige Designlösungen zu entwickeln. Ob Projektleiter, Architekt, Bauunternehmer oder Entwickler – unsere Webanwendung hilft Ihnen, Ihre Arbeitsprozesse zu verbessern und fundierte Entscheidungen zu treffen.",
        start_logIn: "Einloggen in die Non-Plan-Plattform",
        start_loginWelcome1: "Willkommen",
        start_loginWelcome2: "Einloggen in die Non-Plan-Plattform",
        start_forgotPassword: "Passwort vergessen?",
        start_continue: "Weiter",
        start_newAccount: "Noch keinen Account?",
        start_UsernameEmail: "Benutzername oder E-Mail-Adresse",
        start_Password: "Passwort",
        start_Collaborations: "Wir haben stolz mit den folgenden Unternehmen und öffentlichen Institutionen zusammengearbeitet und wirkungsvolle Lösungen geliefert.",
        start_Collaborations2: "Diese Kooperationen zeigen unser Engagement, Innovation und Nachhaltigkeit in der AEC-Branche zu verbinden.",
        start_innovateText2: "Massgeschneiderte digitale Lösungen für Spitzenleistungen im AEC-Bereich: Workflows optimieren, Aufgaben automatisieren und Visualisierung verbessern mit individuellen Tools für Architektur-, Ingenieur- und Bauprofis.(Foto von Marta Buso)",
        start_AR: "Augmented Reality",
        start_AREngie: "Engie Habegger Projekt: Swissbau 2022 AR-Erfahrung.",
        start_ARLiechtenstein: "Universität Liechtenstein Biennale App: Verbindungen von Elektroschrott zwischen Liechtenstein und Ghana hervorheben.(Foto von Marta Buso)",
        start_Hohrainli: "Parametrische Studie zur effizienten Positionierung wiederverwendeter Fassadenelemente, erstellt mit Grasshopper/Python für das Forschungsprojekt GartenPark Hohrainli vom Institut für Umwelt und natürliche Ressourcen an der ZHAW.",
        start_Generator: "Parametrische Studie zur Entwicklung eines Kompatibilitätsprogramms, das verschiedene Räume integriert, inspiriert von Cedric Price und präsentiert an der HSLU Luzern.",
        start_GIS: "GIS-Importer für Archicad: Ein Grasshopper-Skript, beauftragt von OOS, das GIS-Daten wie Topografie und Materialien liest und 3D-Landschaftselemente in Archicad importiert, getrennt nach Material und inklusive Gebäuden.",
        start_Shade: "Schattenüberlappungsrechner für Grasshopper: Ein Skript, beauftragt von OOS, das überlappende Schatten über einen Zeitraum von 3 Stunden berechnet, in Übereinstimmung mit den Vorgaben des Kantons Zürich.",
        start_PythonMat: "Materialraum-Tags für Archicad: Ein Python-Skript, beauftragt von OOS, das Raum-Tags für Materialien direkt in Archicad automatisiert.",
        start_Chaos: "Circular Chaos, eine Anwendung zum Ersetzen von Geometrien aus Listen wiederverwendbarer Elemente.",
        start_ServicesTitle: "Services",
        start_service1Titel: "Plugin-Entwicklung",
        start_service2Titel: "Webanwendungen",
        start_service3Titel: "VR/AR-Apps",
        start_service4Titel: "BIM-Beratung",
        start_service1Content: "Wir entwickeln massgeschneiderte Plugins für Tools wie Archicad, Rhinoceros und Grasshopper, um den spezifischen Anforderungen der AEC-Branche gerecht zu werden. Durch enge Zusammenarbeit mit unseren Kunden identifizieren wir Engpässe und Ineffizienzen und erstellen massgeschneiderte Lösungen, die nahtlos in bestehende Workflows integriert werden. Unsere Plugins verbessern die Funktionalität, vereinfachen repetitive Aufgaben und lösen komplexe Herausforderungen, sodass Ihre Tools leistungsfähiger, anpassungsfähiger und effizienter im Umgang mit anspruchsvollen Design- und Ingenieurprojekten werden.",
        start_service2Content: "Wir entwickeln und bauen individuelle Anwendungen, die Teams befähigen, intelligenter zu arbeiten. Indem wir komplexe Prozesse in benutzerfreundliche Schnittstellen übersetzen, ermöglichen wir Ihnen den Zugriff auf Modelle, Daten und Tools jederzeit und überall. Unsere Lösungen sind kollaborativ, skalierbar und nahtlos in Ihre Workflows integrierbar, wodurch Projektmanagement, Datenvisualisierung und Teamkommunikation effizienter werden. Wir verwandeln Ihre digitale Plattform in ein Tool, das Produktivität steigert und alle auf Kurs hält.",
        start_service3Content: "Nutzen Sie die Kraft von Virtual und Augmented Reality, um Ihre Designs und Präsentationen auf das nächste Level zu heben. Mit Unity entwickeln wir immersive Apps, die es Ihnen ermöglichen, Modelle in Echtzeit zu visualisieren, zu interagieren und zu verfeinern. Ob Sie Materialien erkunden, Designvarianten testen oder Ideen Kunden präsentieren, unsere VR/AR-Lösungen helfen Ihnen, fundierte Entscheidungen zu treffen. Wir schaffen intuitive, eindrucksvolle Erlebnisse, die Projekte zum Leben erwecken und eine bessere Kommunikation und Verständigung ermöglichen.",
        start_service4Content: "Mit jahrelanger Erfahrung im Unterrichten und Arbeiten mit führenden Architekturbüros bieten wir umfassende BIM-Beratungsdienste. Von der Optimierung von Workflows bis hin zur Implementierung fortschrittlicher Modellierungsstrategien, die auf Ihr Unternehmen zugeschnitten sind, helfen wir Ihnen, das volle Potenzial der BIM-Technologie auszuschöpfen. Unsere Expertise stellt sicher, dass Ihre Projekte effizienter geliefert werden, mit weniger Fehlern und besserer Koordination zwischen den Teams. Egal, ob Sie BIM zum ersten Mal einführen oder bestehende Prozesse optimieren möchten, wir bieten die Beratung und Tools, die Sie für den Erfolg benötigen.",
        start_npInfoSoon: "Weitere Informationen folgen in Kürze...",
        start_Mbuso_credit: "Foto von Marta Buso",
        start_OOS_credit: "Skript für das Projekt „Josef will wohnen“, erstellt für OOS."
    }}
    